#!/bin/bash

TRACKER_HELP() {
  echo "tracker CMND ARGS"
  echo "Available commands are:"
  echo "  help    -> Display this text"
  echo "  display -> Display the week"
  echo "             Takes one argument for how many weeks ago (defaults to 0)"
  echo "  create  -> Create a project"
  echo "             Takes one argument for the project name"
  echo "  add     -> Add time to a project"
  echo "             Takes three arguments: The project name, how many hours, and what date (defaults to today)"
  echo "  remove  -> Remove time from a project"
  echo "             Takes three arguments: The project name, how many hours, and what date (defaults to today)"
  echo "  info    -> Display debugging info"
  echo "  list    -> Display all projects and total time"
}

TRACKER_DISPLAY() {
  if [[ $# -lt 1 ]]; then
    echo "Invalid number of arguments (expected 1)"
    exit 2
  elif [[ ! $1 =~ ^[0-9.]+$ ]]; then
    echo "Could not parse argument $1 (expected a number)"
    exit 1
  fi
  tracker.py display $1
}

TRACKER_CREATE() {
  if [[ $# -lt 1 ]]; then
    echo "Invalid number of arguments (expected 1)"
    exit 2
  elif [[ -z $1 ]]; then
    echo "Could not parse argument $1 (expected a non-zero string)"
    exit 1
  fi
  tracker.py create $1
}

TRACKER_ADD() {
  if [[ $# -lt 2 ]]; then
    echo "Invalid number of arguments (expected 2)"
    exit 2
  elif [[ -z $1 ]]; then
    echo "Could not parse argument $1 (expected a non-zero string)"
    exit 1
  elif [[ ! $2 =~ ^[0-9.]+$ ]]; then
    echo "Could not parse argument $2 (expected a number)"
    exit 1
  elif [[ $# -ge 3 && ! $3 =~ ^[0-9.]+$ ]]; then
    echo "Could not parse argument $3 (expected a number)"
    exit 1
  fi
  tracker.py add $1 $2 $3
}

TRACKER_REMOVE() {
  if [[ $# -lt 2 ]]; then
    echo "Invalid number of arguments (expected 2)"
    exit 2
  elif [[ -z $1 ]]; then
    echo "Could not parse argument $1 (expected a non-zero string)"
    exit 1
  elif [[ ! $2 =~ ^[0-9.]+$ ]]; then
    echo "Could not parse argument $2 (expected a number)"
    exit 1
  elif [[ $# -ge 3 && ! $3 =~ ^[0-9.]+$ ]]; then
    echo "Could not parse argument $3 (expected a number)"
    exit 1
  fi
  tracker.py remove $1 $2 $3
}

TRACKER_INFO() {
  tracker.py info
}

TRACKER_LIST() {
  tracker.py list
}

case $1 in
  h|help    ) TRACKER_HELP;;
  d|display ) TRACKER_DISPLAY ${2:-0};;
  c|create  ) TRACKER_CREATE $2;;
  a|add     ) TRACKER_ADD $2 $3 ${4:-0};;
  r|remove  ) TRACKER_REMOVE $2 $3 ${4:-0};;
  i|info    ) TRACKER_INFO;;
  l|list    ) TRACKER_LIST;;
esac

